version: '2'

services:
  db:
    image: mdillon/postgis:9.5
    volumes:
    - db_data:/var/lib/postgresql/data
    ports:
    - "54320:5432"

  app:
    image: skygeario/skygear-server:v1.4.0
    command: skygear-server --http
    ports:
    - "3001:3000"
    volumes:
    - app_data:/go/src/app/data
    depends_on:
    - db
    environment:
      DATABASE_URL: postgresql://postgres:@db/postgres?sslmode=disable
      TOKEN_STORE: jwt
      TOKEN_STORE_SECRET: jwt_secret
      CLOUD_ASSET_PUBLIC_PREFIX: "http://192.168.99.100:3001/files"
      API_KEY: changeme
      MASTER_KEY: secret
      APP_NAME: chuzz
      PLUGINS: PLUGIN
      PLUGIN_TRANSPORT: http
      PLUGIN_PATH: http://plugin:8000
      ASSET_STORE_PUBLIC: "YES"

  plugin:
    build: .
    command: py-skygear --http
    volumes:
    - .:/usr/src/app
    depends_on:
    - app
    environment:
      DATABASE_URL: postgresql://postgres:@db/postgres?sslmode=disable
      SKYGEAR_ADDRESS: tcp://app:5555
      SKYGEAR_ENDPOINT: http://app:3000
      SKYGEAR_MASTERKEY: secret
      SKYGEAR_APPNAME: chuzz
      SKYGEAR_APIKEY: changeme
      API_KEY: changeme
      DATABASE_USERNAME: admin
      DATABASE_PASSWORD: secret
      SCHEMA_NAME: app_chuzz
      APP_NAME: chuzz
      MASTER_KEY: secret
      SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
      CLOUD_ASSET_PUBLIC_PREFIX: "http://192.168.99.100:3001/files"
      ASSET_STORE_PUBLIC: "YES"
      ASSET_STORE: "local"


volumes:
  db_data:
    driver: local
  app_data:
    driver: local
